root: ./docs/

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  dev/read/rpc/eth_callAfter: dev/read/overview.md#available-methods
  dev/read/rpc/eth_getLogsWithCursor: dev/read/overview.md#available-methods
